version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile.client
    depends_on:
      - rabbitmq
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq