services:
  rmq01:
    restart: on-failure
    image: rabbitmq:4.0.4-management
    container_name: rmq01
    hostname: rmq01
    volumes:
      - rmq01-data:/var/lib/rabbitmq/mnesia/
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins 
      - ./config/rabbitmq-init.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf
      - ./config/rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json

  rmq02:
    restart: on-failure
    image: rabbitmq:4.0.4-management
    container_name: rmq02
    hostname: rmq02
    volumes:
      - rmq02-data:/var/lib/rabbitmq/mnesia/
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins 
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf
    depends_on:
      - rmq01

  rmq03:
    restart: on-failure
    image: rabbitmq:4.0.4-management
    container_name: rmq03
    hostname: rmq03
    volumes:
      - rmq03-data:/var/lib/rabbitmq/mnesia/
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins 
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf
    depends_on:
      - rmq01

  haproxy:
    restart: on-failure
    image: haproxy
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq01
      - rmq02
      - rmq03
    ports:
      - 15672:15672
      - 5672:5672

  client01:
    restart: on-failure
    container_name: client01
    environment:
      RABBITMQ_USER: recv01
      RABBITMQ_PASS: recv
    build:
      context: .
      dockerfile: ./Dockerfile.client
    depends_on:
      - rmq01
      - rmq02
      - rmq03

  client02:
    restart: on-failure
    container_name: client02
    environment:
      RABBITMQ_USER: recv02
      RABBITMQ_PASS: recv
    build:
      context: .
      dockerfile: ./Dockerfile.client
    depends_on:
      - rmq01
      - rmq02
      - rmq03

  api:
    restart: on-failure
    container_name: api
    environment:
      RABBITMQ_USER: send
      RABBITMQ_PASS: send
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - '5000:5000'
    depends_on:
      - rmq01
      - rmq02
      - rmq03

volumes:
  rmq01-data:
  rmq02-data:
  rmq03-data: